# Apple Podcasts Bearer Token Extractor
#
# This workflow extracts an Apple Podcasts bearer token using macOS's private
# PodcastsFoundation framework. The token is needed to fetch pre-made transcripts
# from Apple's 125M+ episode library.
#
# IMPORTANT: This workflow should be in a SEPARATE PUBLIC REPO for free macOS runners.
# It's placed here for reference. Copy to your public repo (e.g., apple-token-extractor).
#
# Usage:
#   1. Copy this file to a public GitHub repo
#   2. Go to Actions tab -> "Extract Apple Podcasts Bearer Token"
#   3. Click "Run workflow"
#   4. Download the bearer_token artifact
#   5. Set APPLE_PODCASTS_BEARER_TOKEN in your Vercel env vars
#
# Token renewal: Run monthly (tokens expire after ~30 days)

name: Extract Apple Podcasts Bearer Token

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 6 1 * *'  # 1st of every month at 6:00 AM UTC

jobs:
  extract-token:
    runs-on: macos-15  # macOS 15 (Sequoia) - free for public repos
    timeout-minutes: 10

    steps:
      - name: Check macOS version and available frameworks
        run: |
          echo "=== macOS Version ==="
          sw_vers
          echo ""
          echo "=== Checking for PodcastsFoundation ==="
          if [ -d "/System/Library/PrivateFrameworks/PodcastsFoundation.framework" ]; then
            echo "PodcastsFoundation.framework FOUND"
          else
            echo "PodcastsFoundation.framework NOT FOUND"
            echo "Checking alternative locations..."
            find /System/Library -name "Podcasts*" -type d 2>/dev/null || echo "No Podcasts frameworks found"
          fi

      - name: Clone transcript downloader tool
        run: |
          git clone --depth 1 https://github.com/dado3212/apple-podcast-transcript-downloader.git
          cd apple-podcast-transcript-downloader
          ls -la

      - name: Compile FetchTranscript
        run: |
          cd apple-podcast-transcript-downloader

          # Compile the Objective-C tool linking against PodcastsFoundation
          clang -framework Foundation \
                -F /System/Library/PrivateFrameworks \
                -framework PodcastsFoundation \
                -o FetchTranscript \
                FetchTranscript.m

          echo "Compilation successful!"
          file FetchTranscript

      - name: Extract bearer token
        run: |
          cd apple-podcast-transcript-downloader

          # Use a well-known episode ID for testing (The Daily - NYT)
          # Episode ID 1000683407771 is a recent The Daily episode
          TEST_EPISODE_ID="1000683407771"

          # Run with --cache-bearer-token flag to extract and save the token
          ./FetchTranscript "$TEST_EPISODE_ID" --cache-bearer-token || true

          # Check if bearer token was saved
          if [ -f "bearer_token.txt" ]; then
            echo "Bearer token extracted successfully!"
            TOKEN_LENGTH=$(wc -c < bearer_token.txt)
            echo "Token length: $TOKEN_LENGTH bytes"
            # Show first/last 10 chars for verification (not the full token)
            echo "Token preview: $(head -c 10 bearer_token.txt)...$(tail -c 10 bearer_token.txt)"
          else
            echo "bearer_token.txt not found, checking for token in other locations..."
            # Some versions save to different paths
            find . -name "*.txt" -o -name "*.token" | head -5

            # Try alternative: capture from stdout
            echo "Attempting to extract token from command output..."
            ./FetchTranscript "$TEST_EPISODE_ID" 2>&1 | grep -i "bearer\|token\|authorization" > token_output.txt || true
            if [ -s token_output.txt ]; then
              echo "Found token references in output:"
              cat token_output.txt
            fi
          fi

      - name: Test transcript download
        if: success()
        run: |
          cd apple-podcast-transcript-downloader

          if [ -f "bearer_token.txt" ]; then
            BEARER_TOKEN=$(cat bearer_token.txt)
            TEST_EPISODE_ID="1000683407771"

            # Test fetching a transcript using the token
            echo "Testing transcript fetch for episode $TEST_EPISODE_ID..."
            HTTP_CODE=$(curl -s -o transcript_test.ttml -w "%{http_code}" \
              "https://amp-api.podcasts.apple.com/v1/catalog/us/episodes/${TEST_EPISODE_ID}/transcripts" \
              -H "Authorization: Bearer ${BEARER_TOKEN}" \
              -H "Origin: https://podcasts.apple.com")

            echo "HTTP Status: $HTTP_CODE"

            if [ "$HTTP_CODE" = "200" ]; then
              echo "Transcript fetch successful!"
              echo "Transcript size: $(wc -c < transcript_test.ttml) bytes"
              echo "First 500 chars:"
              head -c 500 transcript_test.ttml
            else
              echo "Transcript fetch failed with status $HTTP_CODE"
              cat transcript_test.ttml 2>/dev/null || true
            fi
          else
            echo "No bearer token available, skipping transcript test"
          fi

      - name: Upload bearer token as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: bearer_token
          path: apple-podcast-transcript-downloader/bearer_token.txt
          retention-days: 90
          if-no-files-found: warn

      - name: Upload test transcript as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test_transcript
          path: apple-podcast-transcript-downloader/transcript_test.ttml
          retention-days: 7
          if-no-files-found: ignore
